name: Commit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      # Fazendo Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      #Configurando PHP
      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml
          coverage: none

      #Composer PHP
      - name: Instalar dependências
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      #Executar os Test com Pest
      - name: Executar testes Pest
        run: ./vendor/bin/pest --colors=always -v --columns=max